name:           lawvere2hs
version:        0.1

ghc-options: -Wall
synopsis: examples in lawvere in haskell

description: |
    code examples as haskell code
dependencies:
  - base >= 4.7 && < 5
  - uniform-strings
#   - uniform-convenience
# #  - test-framework 
#   - QuickCheck
#   - HTF

library:
  source-dirs: .

executables:
  lav:
    main: LawvereMain.hs
    source-dirs: src
    dependencies: 
      lawvere2hs

# tests:
#   test1:
#     main: ExampleTesting.hs
#     source-dirs: tests
#     dependencies: 
#       - TestSimple
# #      - QuickCheck 
# #      - test-framework 

