name:           lawvere2hs
version:        0.1

ghc-options: -Wall
synopsis: examples in lawvere in haskell

description: |
    code examples as haskell code
dependencies:
  - base >= 4.7 && < 5
  - uniformBase
#   - uniform-convenience
# #  - test-framework 
  - QuickCheck
  # - test-simple ==0.1.9

library:
  source-dirs: .

executables:
  lav:
    main: LawvereMain.hs
    source-dirs: src
    dependencies: 
      lawvere2hs

tests:
  test1:
    main: Testing.hs
    source-dirs: tests
    # main: Lib.Lawvere_test.hse
    dependencies: 
      - HTF
      - uniformBase
      # - TestSimple
      # - test-simple
      - QuickCheck 
      # - test-framework 
      - test-invariant
      - numeric-prelude   # for algebra.Lawas
      - lawvere2hs

